### ISSUE TITLE
Recommend writing rake tasks over shell scripts

### ISSUE THREAD

**Issue by azaroth42** [sul-dlss/DeveloperPlaybook#2]
Add:
Recommend rake task over shell script, with reasoning.

**Comment by mejackreed** [comment]
:+1:

**Comment by ndushay** [comment]
:+1:

**Comment by azaroth42** [comment]
@tcramer to provide example rake task ;)

**Comment by eefahy** [comment]
:+1:  on both the issue and @tcramer providing the example

**Comment by jkeck** [comment]
:+1:

**Comment by darrenleeweber** [comment]
:-1: See discussion at https://github.com/sul-dlss/annotations2triannon/pull/10

**Comment by ndushay** [comment]
:+1:    it's weird voting without seeing the "with reasoning" part.  Makes me uncomfy.

**Comment by mejackreed** [comment]
:+1:

**Comment by azaroth42** [comment]
@ndushay Agree regarding the "with reasoning" comment. Happy to work with +1ers to come up with good text for that part in the PR.

**Comment by atz** [comment]
Reasoning: 
- modular, reusable (not copy/paste reusable, _actually_  reusable)
- has access to all app/gem models, config and underlying structure
- testable

I would also submit that **rails console** (i.e. rails command line) code can hit all those points while supporting fuller options/argument handling and depth.  Rake task arguments exist and should be used, but they are nothing compared to real command line expressivity.  

So, prefer rake tasks to shell, yes.  But not prefer *only* rake tasks.

**Comment by azaroth42** [comment]
@atz ... that sounds like a +1 but want to be sure?

**Comment by atz** [comment]
Yes, rake tasks are preferable to shell scripts, generally speaking. :+1:

**Comment by ndushay** [comment]
I would also add that shell scripts aren't cross platform - this is a big reason to prefer rake tasks.

And it's not that I can't come up with the "reasoning" -- it's more that it feels a bit like approving this issue is approving a PR with unknown content.  But that's for a different discussion.  So I remain :+1:  on this issue and retain some concerns about the efficiency of our process -- but am giving it a try, so no flames.

**Comment by drh-stanford** [comment]
:+1:

**Comment by jmartin-sul** [comment]
:+1:

**Comment by jgreben** [comment]
:ok_hand:

**Comment by mjgiarlo** [comment]
Big :+1: on this.

**Comment by mjgiarlo** [comment]
Now that multiple folks have added rationales and agreement, can this be merged?

**Comment by darrenleeweber** [comment]
Is there anything to merge?  (This is an issue.)

**Comment by mjgiarlo** [comment]
Ah, this issue was looking to find consensus. Now we have that, but there is still work to be done. OK, leaving this issue open. Thx, @darrenleeweber.

**Comment by darrenleeweber** [comment]
Perhaps the contribution from @atz is a starting point for a PR?  Also see the discussion in https://github.com/sul-dlss/annotations2triannon/pull/10.  Note that distinctions between apps and gems may be useful.  I'm generally in agreement that rake tasks are preferable.  My objection is based on gem projects where I am using dotenv gem to configure a gem that can be installed (i.e. outside the repo where rake is not available and rake handling/modification of env with dotenv is problematic).  So, while I generally agree rake is preferable, it doesn't cover all cases.

**Comment by mjgiarlo** [comment]
@sul-dlss/infrastructure-team @sul-dlss/access-team @sul-dlss/libsys is this issue still useful or should we dump it?

**Comment by mejackreed** [comment]
🔥

**Comment by jgreben** [comment]
🗑

**Comment by mjgiarlo** [comment]
Closing. Re-open if anyone feels strongly about it.
