### ISSUE TITLE
We communicate effectively

### ISSUE THREAD

**Issue by azaroth42** [sul-dlss/DeveloperPlaybook#22]
We talk with DevOps early and often.  Especially regarding Machines and Security issues

We communicate regarding deployment of code with our team, users and stakeholders

We proactively report bugs in others' code
We enable and encourage others to report bugs in our code
We do so respectfully and with justification
We prefer solutions, especially as PRs, rather than complaints

We report bugs upstream from DLSS 
If possible, we provide solutions, especially as PRs, when doing so or once the issue has been acknowledged
We use github issues in our repos to link to and track upstream bugs that are out of our control

We talk to the Design team as early as possible for UI components and accessibility

**Comment by darrenleeweber** [comment]
:+1:

**Comment by ndushay** [comment]
:-1: as is.   I like the sentiments very much;  I don't like the text as it is.

e.g.:  deployment is very much a DevOps thing too.   Maybe it would be better to let DevOps define their boundaries and involvement?  I would also change the order:  We "proactively report bugs" IMO shouldn't be the top thing in its section -- I would start with how we should behave wrt our own code and then have a separate section on how to behave re: other's code, in the dept and upstream.

I would rather see something like this as a PR so I could comment by the line.  And also see how it is intended to fit into the playbook structure.

**Comment by cbeer** [comment]
:+1: I can live with this list, and am willing to see modifications later. I also think it represents points of consensus from a previous F2F meeting and can be expanded with additional points of consensus later.

I echo @ndushay's interest in having a pull request with this change. I suspect some of the individual points could be addressed before merging if we could easily discuss them point-by-point.

**Comment by mejackreed** [comment]
:+1: I can live with this too.

**Comment by azaroth42** [comment]
@ndushay I did it as an issue rather than a PR to establish consensus on the sentiment rather than the exact text.

Happy to submit a PR, and hope that it will address your issues to generate a :+1:

**Comment by drh-stanford** [comment]
:+1:

**Comment by ndushay** [comment]
I can live w this for now;  will submit PR to massage prose.

**Comment by jmartin-sul** [comment]
:+1:, with some reservations about the actual text, as per @ndushay and @cbeer, but fine overall and totally agree with the sentiment.
