### ISSUE TITLE
Clarify process goals

### ISSUE THREAD

**Issue by azaroth42** [sul-dlss/DeveloperPlaybook#28]
* To provide a catalog current working practices, which are not necessarily *best* practices, just what we do
* To gauge consensus on those working practices, not to argue about whether something is best or not, just whether they're reasonable
* To provide a starting point and default set of expectations, not to mandate or set in stone
* To provide discussion topics, not new hire job requirements
* To provide a set of guides for new hires to learn from, not absolute requirements they must adopt || die()

* The process is broad, imperfect and fast at the outset.  Future discussions can refine, correct and go deep.
* The process can be modified as needed
* Non-substantive changes do not have a waiting period once 4 :+1:s are gathered (e.g. updating an index of links versus creating new content)

[Wording is for sentiment, not final]

**Comment by darrenleeweber** [comment]
Assuming this is superseded by the PR #29

**Comment by ndushay** [comment]
:+1:

**Comment by cbeer** [comment]
Seems inactive and superseded by #29.
