### ISSUE TITLE
Automate ToC generation in the future

### ISSUE THREAD

**Issue by azaroth42** [sul-dlss/DeveloperPlaybook#30]
When the playbook has gathered enough content to be tricky to find what you're looking for we should explore automation of table of contents generation, content search, and other aids.

**Comment by darrenleeweber** [comment]
Consider http://brettterpstra.com/2014/07/01/github-toc-service/  (if it works, it might be enabled with a git commit hook).

**Comment by ndushay** [comment]
:+1:  and "not it!"

**Comment by cbeer** [comment]
Bulk closing inactive issues. Feel free to reopen as needed.
