### ISSUE TITLE
Non-content PRs should ship on 4 +1s

### ISSUE THREAD

**Issue by azaroth42** [sul-dlss/DeveloperPlaybook#31]
Updating non content resources, such as links, table of contents,  typos, etc. should not have to wait a week for a fix.  PRs should note whether they're considered to be non-content, and if others disagree, that should be noted in comments.

[Filing as an issue, as blocked by non-merged #21]

**Comment by mejackreed** [comment]
:+1:

**Comment by darrenleeweber** [comment]
:+1:

**Comment by cbeer** [comment]
:+1:

**Comment by drh-stanford** [comment]
:+1:

**Comment by ndushay** [comment]
:+1:

**Comment by azaroth42** [comment]
Connect to #21

**Comment by ndushay** [comment]
per mtg 2015-06-04:  ready for PR

**Comment by jmartin-sul** [comment]
:+1:

**Comment by jgreben** [comment]
:+1:
