### ISSUE TITLE
Waffle board to facilitate voting

### ISSUE THREAD

**Issue by azaroth42** [sul-dlss/DeveloperPlaybook#33]
I made a waffle board:
    https://waffle.io/sul-dlss/DeveloperPlaybook

So people can easily see which issues need votes, which have hit the two -1s and need discussion and/or closing.  Can just as easily take it down if it's not useful... +1s / -1s?

**Comment by darrenleeweber** [comment]
:+1: so long as it doesn't add extra maintenance;  FYI, I go to https://github.com/notifications while logged in to see items that I could look at.

**Comment by cbeer** [comment]
:+1: I like it as an option. It probably will make any F2F meetings easier.

**Comment by mejackreed** [comment]
:+1:

**Comment by ndushay** [comment]
:+1: :+1:

**Comment by atz** [comment]
:+1: Waffle is good.  Used it for PCDM sprint stuff.

**Comment by drh-stanford** [comment]
:+1:

**Comment by ggeisler** [comment]
:+1:

**Comment by jmartin-sul** [comment]
+0

**Comment by jgreben** [comment]
:ok_hand:
