### ISSUE TITLE
Link to dlss examples

### ISSUE THREAD

**Issue by azaroth42** [sul-dlss/DeveloperPlaybook#34]
Amend the process to include a recommendation that individual entries in the playbook link to repositories, code or other similar DLSS reference examples of the practice's use.  This will help understanding (newcomers can quickly look to see how it was done in the past for real), and keep us honest as to what we actually do and what we'd like to do.

(From @darrenleeweber at https://github.com/sul-dlss/DeveloperPlaybook/pull/29#issuecomment-105930917)

**Comment by cbeer** [comment]
:+1:

**Comment by mejackreed** [comment]
:+1:

**Comment by tingulfsen** [comment]
:+1:

**Comment by jkeck** [comment]
:+1:

**Comment by darrenleeweber** [comment]
:+1: thanks

**Comment by ndushay** [comment]
:+1:   we're talking about links to DLSS code, I assume.

I would say let's even put examples inline when feasible, in addition to links.  ("don't make me go there to decide if I want to go there").   (When this "issue" turns into a PR, that is where inline examples might be mentioned.)

**Comment by azaroth42** [comment]
:+1: to putting examples inline (with link so we can check it in context) when that's a reasonable thing to  do.

**Comment by ndushay** [comment]
per mtg 2015-06-04:  ready for PR

**Comment by drh-stanford** [comment]
:+1:

**Comment by ggeisler** [comment]
:+1:

**Comment by jmartin-sul** [comment]
:+1:

**Comment by jgreben** [comment]
:+1:
