### ISSUE TITLE
DeveloperPlaybook/best-practices/howto_readme.md needs how-to for gemnasium, coveralls etc.?

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/DeveloperPlaybook#42]
I'm looking for additional information on how to enable gemnasium and coveralls for any DLSS project.  Because these are additional online services, it's not obvious to me how we add a DLSS project to these services.  For example, what 'user' account is used for these services?  (If it's a developer's own account, how are they added to a DLSS 'group' (if it exists), and what, if anything, happens during staff turnover etc.)  Would someone qualified like to add this information to the playbook or point me in the right direction if it's already available?

**Comment by darrenleeweber** [comment]
BTW, I know we're trying to prefer PRs over issues, but this can't be a PR and this seems like the best venue for the issue (as opposed to dlss dev list) because it's specifically about the playbook info.

**Comment by mejackreed** [comment]
I think that you need to have @sul-devops-team register your app with Gemnasium

https://consul.stanford.edu/display/dlssdevops/How+to+track+and+manage+application+dependencies

For Coveralls, I have followed this guide to adding them into the apps I work on:

https://coveralls.zendesk.com/hc/en-us/articles/201769485-Ruby-Rails

**Comment by jkeck** [comment]
Also, you'll probably want to add a Service to your repository so that it informs Gemnasium when you've updated so it will re-evaluate your Gemfile.lock.

This is particularly useful when you're using the Gemnasium badge on your README otherwise it will be stale.

**Comment by jkeck** [comment]
Service Setup Example: https://github.com/sul-dlss/sul-requests/settings/hooks

**Comment by azaroth42** [comment]
Meta: :+1: to raising issues for shared requirements that aren't in the playbook!

**Comment by darrenleeweber** [comment]
See PR #42 as a first attempt to include the core of these comments in the how-to.

**Comment by mjgiarlo** [comment]
@darrenleeweber With #44 merged, can this be closed or should it be amended?

**Comment by darrenleeweber** [comment]
Closing.
