### ISSUE TITLE
Integrate consul documentation about deployment practices

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/DeveloperPlaybook#45]
See
- https://consul.stanford.edu/x/4TJJC

Also consider these notes that helped me resolve some problems with SDR app deployments:
- https://consul.stanford.edu/x/B-RdC

**Comment by mjgiarlo** [comment]
:+1:

**Comment by SaravShah** [comment]
https://github.com/sul-dlss/DeveloperPlaybook/blob/master/best-practices/deployment.md
