### ISSUE TITLE
Section for editors and IDEs

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/DeveloperPlaybook#47]
We often have useful tips and tricks for using an editor or an IDE.  The playbook might be a good venue for documenting and sharing.

**Comment by darrenleeweber** [comment]
For example, I have some notes on useful packages for for sublime text 3, i.e.

Sublime Text 3 packages
- package control
  - https://packagecontrol.io/installation#st3
- sublime linter
  - https://github.com/SublimeLinter
  - https://github.com/SublimeLinter/SublimeLinter3
  - http://sublimelinter.readthedocs.org/en/latest/
- vintageous
  -https://github.com/guillermooo/Vintageous
- Git
  - https://packagecontrol.io/packages/GitGutter
- ruby & rails
  - https://mattbrictson.com/sublime-text-3-recommendations
  - allautocomplete
  - https://packagecontrol.io/packages/DocBlockr
  - https://github.com/SublimeLinter/SublimeLinter-ruby
  - https://github.com/SublimeLinter/SublimeLinter-rubocop
- OSX
  - Dash
    - https://kapeli.com/dash
    - https://github.com/farcaller/DashDoc#readme

**Comment by mjgiarlo** [comment]
An "IDE recipes" area would be quite useful, @darrenleeweber. Can you want to contribute that as a PR?

**Comment by darrenleeweber** [comment]
I'm wondering whether these is anything that would be DLSS recommendations or requirements that are specific to an IDE.  Unless it's DLSS-ish, it probably shouldn't be in the playbook.

**Comment by mejackreed** [comment]
Maybe a place to share our setups? I don't think there would ever be a requirement. Seems like sharing information about this could be useful

**Comment by darrenleeweber** [comment]
As you can see above, I'm using a gist (above) and that's not DLSS specific.  I guess the idea here was things like config files and that problem has since been solved with the shared_configs repo (hooray!).  Anything like DLSS specific setup could make life a bit easier.  Maybe a wiki section, but it might have to be private.
