### ISSUE TITLE
Provide guidelines for version control workflow

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/DeveloperPlaybook#48]
e.g., git flow, github flow, and others.

**Comment by darrenleeweber** [comment]
:+1:  esp. with a template blurb in a README.md or starter/template repo

**Comment by camillevilla** [comment]
https://github.com/sul-dlss/DeveloperPlaybook/blob/master/best-practices/version_control.md

Closing this issue for now, feel free to make more specific suggestions via new issues.
