### ISSUE TITLE
12 factor apps

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/DeveloperPlaybook#6]
See http://12factor.net/

**Comment by azaroth42** [comment]
Please specify what the proposal is?

**Comment by azaroth42** [comment]
As a process, I suggest we look at the 12 factors and see which apply to us and what our current practices (best or not) are.

For example, I think we do follow their Codebase process (http://12factor.net/codebase), whereas we don't follow their Config practice of storing configuration in environment variables.

**Comment by darrenleeweber** [comment]
Who is 'we'?  I do follow their practice of storing configs in ENV and I do want to follow it.

**Comment by darrenleeweber** [comment]
Here's a concrete example of using ENV to configure a gem.  See
  - https://github.com/sul-dlss/triannon-client#configuration
  - https://github.com/sul-dlss/triannon-client/blob/master/lib/triannon-client.rb#L1-L2
  - https://github.com/sul-dlss/triannon-client/blob/master/lib/triannon-client/configuration.rb

The default values are defined in ruby in lib/triannon-client/configuration.rb but they can be modified in several ways, including ENV values set on the system, ENV values set in a shell, ENV values set on a command line, and then attribute setters on the config object.  This is a very flexible system.

**Comment by azaroth42** [comment]
We is DLSS :) My proposal was that we determine what we (DLSS as a whole) do and don't do. I suggest one issue per factor to avoid it being untrackable.  The current phase is to determine current working practices that are shared.

**Comment by darrenleeweber** [comment]
So we need 12 issues/PR for this?

**Comment by ndushay** [comment]
:-1:  this predates our 2015-05-21 meeting.  It is too vague for me to even evaluate what it is.  I don't want to have to spend 2 hours reading stuff to vote on an issue -- I prefer them shorter with relevant information inline (and with sources indicated) rather than "go to these 10 links".

**Comment by azaroth42** [comment]
For this issue...
:-1: because it's too large to evaluate, determine which parts are relevant, and which parts we have consensus on.

**Comment by cbeer** [comment]
Bulk closing inactive issues. Feel free to reopen as needed.
